/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QFrame *line_7;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QFrame *line_11;
    QFrame *line_12;
    QFrame *line_13;
    QFrame *line_14;
    QFrame *line_15;
    QFrame *line_16;
    QFrame *line_17;
    QFrame *line_18;
    QFrame *line_19;
    QFrame *line_20;
    QFrame *line_21;
    QPushButton *enter;
    QPushButton *exit;
    QLabel *enterLabel;
    QLabel *exitLabel;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *spot;
    QFrame *line_22;
    QFrame *enterline;
    QFrame *line_23;
    QFrame *exitline;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *label_6;
    QLabel *label_15;
    QLabel *label_16;
    QFrame *line_24;
    QFrame *line_25;
    QFrame *line_26;
    QFrame *line_27;
    QFrame *line_28;
    QFrame *line_32;
    QFrame *line_29;
    QFrame *line_30;
    QFrame *line_31;
    QGroupBox *singleLight;
    QLabel *red;
    QLabel *yellow;
    QLabel *green;
    QLCDNumber *lcdNumber;
    QGroupBox *singleLight_2;
    QLabel *red_2;
    QLabel *yellow_2;
    QLabel *green_2;
    QLCDNumber *lcdNumber_2;
    QGroupBox *singleLight_3;
    QLabel *red_3;
    QLabel *yellow_3;
    QLabel *green_3;
    QLCDNumber *lcdNumber_3;
    QFrame *line_33;
    QFrame *line_34;
    QFrame *line_35;
    QFrame *line_36;
    QGroupBox *singleLight_4;
    QLabel *red_4;
    QLabel *yellow_4;
    QLabel *green_4;
    QLCDNumber *lcdNumber_4;
    QLabel *car;
    QLabel *car1;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1124, 903);
        QPalette palette;
        QBrush brush(QColor(85, 255, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        MainWindow->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("\347\255\211\347\272\277 Light"));
        font.setBold(false);
        font.setWeight(50);
        MainWindow->setFont(font);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        line = new QFrame(centralWidget);
        line->setObjectName(QStringLiteral("line"));
        line->setGeometry(QRect(250, 350, 20, 361));
        line->setFrameShape(QFrame::VLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(340, 350, 20, 181));
        line_2->setFrameShape(QFrame::VLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QStringLiteral("line_3"));
        line_3->setGeometry(QRect(350, 520, 411, 16));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QStringLiteral("line_4"));
        line_4->setGeometry(QRect(260, 620, 411, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(centralWidget);
        line_5->setObjectName(QStringLiteral("line_5"));
        line_5->setGeometry(QRect(660, 630, 16, 141));
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralWidget);
        line_6->setObjectName(QStringLiteral("line_6"));
        line_6->setGeometry(QRect(750, 450, 20, 321));
        line_6->setFrameShape(QFrame::VLine);
        line_6->setFrameShadow(QFrame::Sunken);
        line_7 = new QFrame(centralWidget);
        line_7->setObjectName(QStringLiteral("line_7"));
        line_7->setGeometry(QRect(260, 570, 501, 16));
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        line_8 = new QFrame(centralWidget);
        line_8->setObjectName(QStringLiteral("line_8"));
        line_8->setGeometry(QRect(350, 440, 411, 16));
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralWidget);
        line_9->setObjectName(QStringLiteral("line_9"));
        line_9->setGeometry(QRect(257, 700, 411, 20));
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralWidget);
        line_10->setObjectName(QStringLiteral("line_10"));
        line_10->setGeometry(QRect(400, 450, 16, 81));
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        line_11 = new QFrame(centralWidget);
        line_11->setObjectName(QStringLiteral("line_11"));
        line_11->setGeometry(QRect(460, 450, 16, 81));
        line_11->setFrameShape(QFrame::VLine);
        line_11->setFrameShadow(QFrame::Sunken);
        line_12 = new QFrame(centralWidget);
        line_12->setObjectName(QStringLiteral("line_12"));
        line_12->setGeometry(QRect(520, 450, 16, 81));
        line_12->setFrameShape(QFrame::VLine);
        line_12->setFrameShadow(QFrame::Sunken);
        line_13 = new QFrame(centralWidget);
        line_13->setObjectName(QStringLiteral("line_13"));
        line_13->setGeometry(QRect(580, 450, 16, 81));
        line_13->setFrameShape(QFrame::VLine);
        line_13->setFrameShadow(QFrame::Sunken);
        line_14 = new QFrame(centralWidget);
        line_14->setObjectName(QStringLiteral("line_14"));
        line_14->setGeometry(QRect(640, 450, 16, 81));
        line_14->setFrameShape(QFrame::VLine);
        line_14->setFrameShadow(QFrame::Sunken);
        line_15 = new QFrame(centralWidget);
        line_15->setObjectName(QStringLiteral("line_15"));
        line_15->setGeometry(QRect(690, 450, 16, 81));
        line_15->setFrameShape(QFrame::VLine);
        line_15->setFrameShadow(QFrame::Sunken);
        line_16 = new QFrame(centralWidget);
        line_16->setObjectName(QStringLiteral("line_16"));
        line_16->setGeometry(QRect(320, 630, 16, 81));
        line_16->setFrameShape(QFrame::VLine);
        line_16->setFrameShadow(QFrame::Sunken);
        line_17 = new QFrame(centralWidget);
        line_17->setObjectName(QStringLiteral("line_17"));
        line_17->setGeometry(QRect(370, 630, 16, 81));
        line_17->setFrameShape(QFrame::VLine);
        line_17->setFrameShadow(QFrame::Sunken);
        line_18 = new QFrame(centralWidget);
        line_18->setObjectName(QStringLiteral("line_18"));
        line_18->setGeometry(QRect(430, 630, 16, 81));
        line_18->setFrameShape(QFrame::VLine);
        line_18->setFrameShadow(QFrame::Sunken);
        line_19 = new QFrame(centralWidget);
        line_19->setObjectName(QStringLiteral("line_19"));
        line_19->setGeometry(QRect(490, 630, 16, 81));
        line_19->setFrameShape(QFrame::VLine);
        line_19->setFrameShadow(QFrame::Sunken);
        line_20 = new QFrame(centralWidget);
        line_20->setObjectName(QStringLiteral("line_20"));
        line_20->setGeometry(QRect(550, 630, 16, 81));
        line_20->setFrameShape(QFrame::VLine);
        line_20->setFrameShadow(QFrame::Sunken);
        line_21 = new QFrame(centralWidget);
        line_21->setObjectName(QStringLiteral("line_21"));
        line_21->setGeometry(QRect(600, 630, 16, 81));
        line_21->setFrameShape(QFrame::VLine);
        line_21->setFrameShadow(QFrame::Sunken);
        enter = new QPushButton(centralWidget);
        enter->setObjectName(QStringLiteral("enter"));
        enter->setGeometry(QRect(260, 450, 81, 28));
        exit = new QPushButton(centralWidget);
        exit->setObjectName(QStringLiteral("exit"));
        exit->setGeometry(QRect(670, 690, 81, 28));
        enterLabel = new QLabel(centralWidget);
        enterLabel->setObjectName(QStringLiteral("enterLabel"));
        enterLabel->setGeometry(QRect(0, 450, 261, 171));
        enterLabel->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"font: 75 12pt \"\351\273\221\344\275\223\";\n"
"\n"
"color: rgb(0, 170, 0);"));
        exitLabel = new QLabel(centralWidget);
        exitLabel->setObjectName(QStringLiteral("exitLabel"));
        exitLabel->setGeometry(QRect(760, 550, 261, 171));
        exitLabel->setStyleSheet(QString::fromUtf8("background-color: rgb(0, 0, 0);\n"
"font: 75 12pt \"\351\273\221\344\275\223\";\n"
"\n"
"color: rgb(0, 170, 0);"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(350, 450, 51, 71));
        label->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(470, 450, 51, 71));
        label_2->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(590, 450, 51, 71));
        label_3->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(700, 450, 51, 71));
        label_4->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(270, 630, 51, 71));
        label_5->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(500, 630, 51, 71));
        label_7->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(610, 630, 51, 71));
        label_8->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(410, 450, 51, 71));
        label_9->setMaximumSize(QSize(51, 16777215));
        label_9->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(530, 450, 51, 71));
        label_10->setMaximumSize(QSize(51, 16777215));
        label_10->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(440, 630, 51, 71));
        label_11->setMaximumSize(QSize(51, 16777215));
        label_11->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(560, 630, 41, 71));
        label_12->setMaximumSize(QSize(51, 16777215));
        label_12->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(330, 630, 41, 71));
        label_13->setMaximumSize(QSize(51, 16777215));
        label_13->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(650, 450, 41, 71));
        label_14->setMaximumSize(QSize(51, 16777215));
        label_14->setStyleSheet(QString::fromUtf8("\n"
"background-image: url(:/new/prefix1/picture/\350\215\211\345\235\2522975.jpg);"));
        spot = new QLabel(centralWidget);
        spot->setObjectName(QStringLiteral("spot"));
        spot->setGeometry(QRect(380, 630, 51, 71));
        spot->setStyleSheet(QStringLiteral("background-color: rgb(85, 255, 0);"));
        line_22 = new QFrame(centralWidget);
        line_22->setObjectName(QStringLiteral("line_22"));
        line_22->setGeometry(QRect(220, 400, 20, 31));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\346\226\271\346\255\243\347\262\227\351\273\221\345\256\213\347\256\200\344\275\223"));
        font1.setBold(false);
        font1.setWeight(50);
        line_22->setFont(font1);
        line_22->setFrameShadow(QFrame::Plain);
        line_22->setLineWidth(5);
        line_22->setFrameShape(QFrame::VLine);
        enterline = new QFrame(centralWidget);
        enterline->setObjectName(QStringLiteral("enterline"));
        enterline->setGeometry(QRect(230, 410, 121, 16));
        enterline->setFrameShadow(QFrame::Plain);
        enterline->setLineWidth(5);
        enterline->setFrameShape(QFrame::HLine);
        line_23 = new QFrame(centralWidget);
        line_23->setObjectName(QStringLiteral("line_23"));
        line_23->setGeometry(QRect(780, 730, 16, 31));
        line_23->setFrameShadow(QFrame::Plain);
        line_23->setLineWidth(5);
        line_23->setFrameShape(QFrame::VLine);
        exitline = new QFrame(centralWidget);
        exitline->setObjectName(QStringLiteral("exitline"));
        exitline->setGeometry(QRect(667, 740, 121, 20));
        exitline->setFrameShadow(QFrame::Plain);
        exitline->setLineWidth(5);
        exitline->setFrameShape(QFrame::HLine);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(270, 420, 71, 28));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(680, 720, 71, 28));
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(150, 410, 72, 15));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(800, 740, 72, 15));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(450, 560, 131, 41));
        QFont font2;
        font2.setPointSize(13);
        font2.setBold(true);
        font2.setWeight(75);
        label_16->setFont(font2);
        line_24 = new QFrame(centralWidget);
        line_24->setObjectName(QStringLiteral("line_24"));
        line_24->setGeometry(QRect(690, 220, 321, 20));
        line_24->setFrameShape(QFrame::HLine);
        line_24->setFrameShadow(QFrame::Sunken);
        line_25 = new QFrame(centralWidget);
        line_25->setObjectName(QStringLiteral("line_25"));
        line_25->setGeometry(QRect(690, 280, 321, 20));
        line_25->setFrameShape(QFrame::HLine);
        line_25->setFrameShadow(QFrame::Sunken);
        line_26 = new QFrame(centralWidget);
        line_26->setObjectName(QStringLiteral("line_26"));
        line_26->setGeometry(QRect(690, 340, 321, 20));
        line_26->setFrameShape(QFrame::HLine);
        line_26->setFrameShadow(QFrame::Sunken);
        line_27 = new QFrame(centralWidget);
        line_27->setObjectName(QStringLiteral("line_27"));
        line_27->setGeometry(QRect(0, 340, 261, 20));
        line_27->setFrameShape(QFrame::HLine);
        line_27->setFrameShadow(QFrame::Sunken);
        line_28 = new QFrame(centralWidget);
        line_28->setObjectName(QStringLiteral("line_28"));
        line_28->setGeometry(QRect(540, 80, 20, 151));
        line_28->setFrameShape(QFrame::VLine);
        line_28->setFrameShadow(QFrame::Sunken);
        line_32 = new QFrame(centralWidget);
        line_32->setObjectName(QStringLiteral("line_32"));
        line_32->setGeometry(QRect(680, 80, 20, 151));
        line_32->setFrameShape(QFrame::VLine);
        line_32->setFrameShadow(QFrame::Sunken);
        line_29 = new QFrame(centralWidget);
        line_29->setObjectName(QStringLiteral("line_29"));
        line_29->setGeometry(QRect(0, 220, 551, 20));
        line_29->setFrameShape(QFrame::HLine);
        line_29->setFrameShadow(QFrame::Sunken);
        line_30 = new QFrame(centralWidget);
        line_30->setObjectName(QStringLiteral("line_30"));
        line_30->setGeometry(QRect(0, 280, 551, 20));
        line_30->setFrameShape(QFrame::HLine);
        line_30->setFrameShadow(QFrame::Sunken);
        line_31 = new QFrame(centralWidget);
        line_31->setObjectName(QStringLiteral("line_31"));
        line_31->setGeometry(QRect(610, 80, 20, 151));
        line_31->setFrameShape(QFrame::VLine);
        line_31->setFrameShadow(QFrame::Sunken);
        singleLight = new QGroupBox(centralWidget);
        singleLight->setObjectName(QStringLiteral("singleLight"));
        singleLight->setGeometry(QRect(540, 200, 151, 31));
        red = new QLabel(singleLight);
        red->setObjectName(QStringLiteral("red"));
        red->setGeometry(QRect(10, 10, 21, 20));
        red->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/red.jpg);"));
        red->setScaledContents(true);
        red->setWordWrap(false);
        red->setMargin(2);
        red->setTextInteractionFlags(Qt::LinksAccessibleByKeyboard|Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard);
        yellow = new QLabel(singleLight);
        yellow->setObjectName(QStringLiteral("yellow"));
        yellow->setGeometry(QRect(40, 10, 21, 21));
        yellow->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/yellow.jpg);"));
        yellow->setScaledContents(true);
        green = new QLabel(singleLight);
        green->setObjectName(QStringLiteral("green"));
        green->setGeometry(QRect(70, 10, 20, 21));
        green->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/green.jpg);"));
        green->setScaledContents(true);
        lcdNumber = new QLCDNumber(singleLight);
        lcdNumber->setObjectName(QStringLiteral("lcdNumber"));
        lcdNumber->setGeometry(QRect(100, 0, 51, 31));
        QFont font3;
        font3.setFamily(QStringLiteral("Times New Roman"));
        font3.setPointSize(26);
        font3.setBold(false);
        font3.setItalic(false);
        font3.setWeight(9);
        lcdNumber->setFont(font3);
        lcdNumber->setContextMenuPolicy(Qt::CustomContextMenu);
        lcdNumber->setAcceptDrops(true);
        lcdNumber->setStyleSheet(QStringLiteral("font: 75 26pt \"Times New Roman\";"));
        lcdNumber->setSmallDecimalPoint(false);
        lcdNumber->setDigitCount(4);
        lcdNumber->setSegmentStyle(QLCDNumber::Filled);
        singleLight_2 = new QGroupBox(centralWidget);
        singleLight_2->setObjectName(QStringLiteral("singleLight_2"));
        singleLight_2->setGeometry(QRect(500, 230, 51, 121));
        red_2 = new QLabel(singleLight_2);
        red_2->setObjectName(QStringLiteral("red_2"));
        red_2->setGeometry(QRect(30, 0, 21, 20));
        red_2->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/red.jpg);"));
        red_2->setScaledContents(true);
        red_2->setWordWrap(false);
        red_2->setMargin(2);
        red_2->setTextInteractionFlags(Qt::LinksAccessibleByKeyboard|Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard);
        yellow_2 = new QLabel(singleLight_2);
        yellow_2->setObjectName(QStringLiteral("yellow_2"));
        yellow_2->setGeometry(QRect(30, 30, 21, 21));
        yellow_2->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/yellow.jpg);"));
        yellow_2->setScaledContents(true);
        green_2 = new QLabel(singleLight_2);
        green_2->setObjectName(QStringLiteral("green_2"));
        green_2->setGeometry(QRect(30, 60, 20, 21));
        green_2->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/green.jpg);"));
        green_2->setScaledContents(true);
        lcdNumber_2 = new QLCDNumber(singleLight_2);
        lcdNumber_2->setObjectName(QStringLiteral("lcdNumber_2"));
        lcdNumber_2->setGeometry(QRect(0, 90, 51, 31));
        lcdNumber_2->setFont(font3);
        lcdNumber_2->setContextMenuPolicy(Qt::CustomContextMenu);
        lcdNumber_2->setAcceptDrops(true);
        lcdNumber_2->setLayoutDirection(Qt::LeftToRight);
        lcdNumber_2->setStyleSheet(QStringLiteral("font: 75 26pt \"Times New Roman\";"));
        lcdNumber_2->setSmallDecimalPoint(false);
        lcdNumber_2->setDigitCount(4);
        lcdNumber_2->setSegmentStyle(QLCDNumber::Filled);
        singleLight_3 = new QGroupBox(centralWidget);
        singleLight_3->setObjectName(QStringLiteral("singleLight_3"));
        singleLight_3->setGeometry(QRect(690, 230, 51, 121));
        red_3 = new QLabel(singleLight_3);
        red_3->setObjectName(QStringLiteral("red_3"));
        red_3->setGeometry(QRect(0, 0, 21, 20));
        red_3->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/red.jpg);"));
        red_3->setScaledContents(true);
        red_3->setWordWrap(false);
        red_3->setMargin(2);
        red_3->setTextInteractionFlags(Qt::LinksAccessibleByKeyboard|Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard);
        yellow_3 = new QLabel(singleLight_3);
        yellow_3->setObjectName(QStringLiteral("yellow_3"));
        yellow_3->setGeometry(QRect(0, 30, 21, 21));
        yellow_3->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/yellow.jpg);"));
        yellow_3->setScaledContents(true);
        green_3 = new QLabel(singleLight_3);
        green_3->setObjectName(QStringLiteral("green_3"));
        green_3->setGeometry(QRect(0, 60, 20, 21));
        green_3->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/green.jpg);"));
        green_3->setScaledContents(true);
        lcdNumber_3 = new QLCDNumber(singleLight_3);
        lcdNumber_3->setObjectName(QStringLiteral("lcdNumber_3"));
        lcdNumber_3->setGeometry(QRect(0, 90, 51, 31));
        lcdNumber_3->setFont(font3);
        lcdNumber_3->setContextMenuPolicy(Qt::CustomContextMenu);
        lcdNumber_3->setAcceptDrops(true);
        lcdNumber_3->setLayoutDirection(Qt::LeftToRight);
        lcdNumber_3->setStyleSheet(QStringLiteral("font: 75 26pt \"Times New Roman\";"));
        lcdNumber_3->setSmallDecimalPoint(false);
        lcdNumber_3->setDigitCount(4);
        lcdNumber_3->setSegmentStyle(QLCDNumber::Filled);
        line_33 = new QFrame(centralWidget);
        line_33->setObjectName(QStringLiteral("line_33"));
        line_33->setGeometry(QRect(540, 350, 20, 71));
        line_33->setFrameShape(QFrame::VLine);
        line_33->setFrameShadow(QFrame::Sunken);
        line_34 = new QFrame(centralWidget);
        line_34->setObjectName(QStringLiteral("line_34"));
        line_34->setGeometry(QRect(610, 350, 20, 71));
        line_34->setFrameShape(QFrame::VLine);
        line_34->setFrameShadow(QFrame::Sunken);
        line_35 = new QFrame(centralWidget);
        line_35->setObjectName(QStringLiteral("line_35"));
        line_35->setGeometry(QRect(680, 350, 20, 71));
        line_35->setFrameShape(QFrame::VLine);
        line_35->setFrameShadow(QFrame::Sunken);
        line_36 = new QFrame(centralWidget);
        line_36->setObjectName(QStringLiteral("line_36"));
        line_36->setGeometry(QRect(350, 340, 201, 20));
        line_36->setFrameShape(QFrame::HLine);
        line_36->setFrameShadow(QFrame::Sunken);
        singleLight_4 = new QGroupBox(centralWidget);
        singleLight_4->setObjectName(QStringLiteral("singleLight_4"));
        singleLight_4->setGeometry(QRect(540, 350, 151, 31));
        red_4 = new QLabel(singleLight_4);
        red_4->setObjectName(QStringLiteral("red_4"));
        red_4->setGeometry(QRect(10, 0, 21, 20));
        red_4->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/red.jpg);"));
        red_4->setScaledContents(true);
        red_4->setWordWrap(false);
        red_4->setMargin(2);
        red_4->setTextInteractionFlags(Qt::LinksAccessibleByKeyboard|Qt::LinksAccessibleByMouse|Qt::TextSelectableByKeyboard);
        yellow_4 = new QLabel(singleLight_4);
        yellow_4->setObjectName(QStringLiteral("yellow_4"));
        yellow_4->setGeometry(QRect(40, 0, 21, 21));
        yellow_4->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/yellow.jpg);"));
        yellow_4->setScaledContents(true);
        green_4 = new QLabel(singleLight_4);
        green_4->setObjectName(QStringLiteral("green_4"));
        green_4->setGeometry(QRect(70, 0, 20, 21));
        green_4->setStyleSheet(QStringLiteral("image: url(:/new/prefix1/picture/green.jpg);"));
        green_4->setScaledContents(true);
        lcdNumber_4 = new QLCDNumber(singleLight_4);
        lcdNumber_4->setObjectName(QStringLiteral("lcdNumber_4"));
        lcdNumber_4->setGeometry(QRect(100, 0, 51, 31));
        lcdNumber_4->setFont(font3);
        lcdNumber_4->setContextMenuPolicy(Qt::CustomContextMenu);
        lcdNumber_4->setAcceptDrops(true);
        lcdNumber_4->setStyleSheet(QStringLiteral("font: 75 26pt \"Times New Roman\";"));
        lcdNumber_4->setSmallDecimalPoint(false);
        lcdNumber_4->setDigitCount(4);
        lcdNumber_4->setSegmentStyle(QLCDNumber::Filled);
        car = new QLabel(centralWidget);
        car->setObjectName(QStringLiteral("car"));
        car->setGeometry(QRect(940, 230, 72, 71));
        car->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/picture/zuo.png")));
        car1 = new QLabel(centralWidget);
        car1->setObjectName(QStringLiteral("car1"));
        car1->setGeometry(QRect(570, 0, 72, 61));
        car1->setLayoutDirection(Qt::LeftToRight);
        car1->setPixmap(QPixmap(QString::fromUtf8(":/new/prefix1/picture/xia.png")));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1124, 26));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        enter->setText(QApplication::translate("MainWindow", "\345\205\245\345\217\243\346\211\253\346\217\217", 0));
        exit->setText(QApplication::translate("MainWindow", "\345\207\272\345\217\243\346\211\253\346\217\217", 0));
        enterLabel->setText(QApplication::translate("MainWindow", "\345\205\245\345\217\243\346\230\276\347\244\272", 0));
        exitLabel->setText(QApplication::translate("MainWindow", "\345\207\272\345\217\243\346\230\276\347\244\272", 0));
        label->setText(QApplication::translate("MainWindow", "  A1", 0));
        label_2->setText(QApplication::translate("MainWindow", "  A2", 0));
        label_3->setText(QApplication::translate("MainWindow", " A3", 0));
        label_4->setText(QApplication::translate("MainWindow", "  A4", 0));
        label_5->setText(QApplication::translate("MainWindow", "  A5", 0));
        label_7->setText(QApplication::translate("MainWindow", "  A7", 0));
        label_8->setText(QApplication::translate("MainWindow", "  A8", 0));
        label_9->setText(QString());
        label_10->setText(QString());
        label_11->setText(QString());
        label_12->setText(QString());
        label_13->setText(QString());
        label_14->setText(QString());
        spot->setText(QApplication::translate("MainWindow", "  A6", 0));
        pushButton->setText(QApplication::translate("MainWindow", "\347\272\242\345\244\226", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "\347\272\242\345\244\226", 0));
        label_6->setText(QApplication::translate("MainWindow", "\346\240\205\346\240\217--->", 0));
        label_15->setText(QApplication::translate("MainWindow", "<---\346\240\205\346\240\217", 0));
        label_16->setText(QApplication::translate("MainWindow", "      \345\201\234 \350\275\246 \345\234\272", 0));
        singleLight->setTitle(QString());
        red->setText(QString());
        yellow->setText(QString());
        green->setText(QString());
        singleLight_2->setTitle(QString());
        red_2->setText(QString());
        yellow_2->setText(QString());
        green_2->setText(QString());
        singleLight_3->setTitle(QString());
        red_3->setText(QString());
        yellow_3->setText(QString());
        green_3->setText(QString());
        singleLight_4->setTitle(QString());
        red_4->setText(QString());
        yellow_4->setText(QString());
        green_4->setText(QString());
        car->setText(QString());
        car1->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
